### ISSUE TITLE
Problema no EquipRequest 

### ISSUE THREAD

**Issue by mbnunes** [UltimaPHP/UltimaPHP#77]
**Client Version**
Client version 7.0.80.0

**Describe the bug**
Eu estava equipado com um Axe e ao arrastar ele para o chão, ele sumiu, e quando eu criei um outro Axe e equipei, ele foi para LAYER 2 e nao para LAYER 1, quando removi o segundo axe para o chão e dei dois cliques nele, o primeiro Axe apareceu no chao aonde eu estava qndo ele sumiu ai o segundo Axe comecou a ir para Layer 1

**Comment by joaoescribano** [comment]
It was fixed in the last commit https://github.com/UltimaPHP/UltimaPHP/commit/d1b961b0805dd9687a438cbb97dc20a9e984e92b

The issue was that the Axe wasn't implemented as a type or any layer so the equipRequest doesn't know what to do with it.
I've made a change to the code so now (assuming the player "grabbed" the item already at hands) when the player drags the item to the layer at the paper doll, the server checks for its layer if it doesn't fit the layer, it will send the item back to the player's backpack.

It needs improvements, like checking the weight to put on the backpack or drop on the ground.
